"""add document status

Revision ID: 55ecd55aaba3
Revises: 907fd9246a16
Create Date: 2026-06-08 08:14:34.739369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ecd55aaba3'
down_revision: Union[str, Sequence[str], None] = '907fd9246a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.Enum('PROCESSING', 'READY', 'FAILED', name='documentstatus'), nullable=False,server_default="PROCESSING"))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
